name: CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Lấy code từ repo
      - uses: actions/checkout@v3

      # Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Cài dependencies
      - name: Install dependencies
        run: npm install

      # Build project ra dist/
      - name: Build project
        run: npm run build

      # Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          allow_empty_commit: true
          keep_files: true
          enable_jekyll: false
