name: CI/CD

# Kích hoạt workflow khi push lên main
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Cài dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # thư mục build output
          publish_branch: gh-pages # branch deploy
          force_orphan: true # tạo branch mới nếu chưa có
          allow_empty_commit: true # commit nếu không có thay đổi
          keep_files: true # không xóa file tạm trong runner
          enable_jekyll: false # tắt Jekyll
