name: Build TodoApp

# Kích hoạt workflow khi push vào main
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Cài dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build project
      - name: Build project
        run: npm run build

      # 5️⃣ (Optional) Upload artifact để download nếu cần
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: todoapp-dist
          path: ./dist
